export interface InvestModel {
    _id: number,
    titreoperation: string,
    entreprise: string,
    annee_de_livraison: number,
    ville: string,
    mandataire: string,
    ppi: string,
    lycee: string,
    notification_du_marche: number,
    codeuai: string,
    longitude: number,
    etat_d_avancement: string,
    montant_des_ap_votes_en_meu: number,
    cao_attribution: number,
    latitude: number,
    maitrise_d_oeuvre: string,
    mode_de_devolution: string,
    annee_d_individualisation: number,
    enveloppe_prev_en_meu: number
}